server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/imagedb
    username: root
    password: pass
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop


bucket:
  properties:
    name: ""
    access-key-id: ""
    secret-access-key: ""
    storage-path: "https://storage.yandexcloud.net/"

jwt:
  secret: secretkeyPasswordForAuth12312312312313213123123sdfsdf
