server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postsDB
    username: root
    password: pass
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

